### ISSUE TITLE
Add all softwares listed under AnythingMC

### ISSUE THREAD

**Issue by LeStegii** [LeStegii/server-softwares#24]
- Look at all the softwares listed under [AnythingsMC's software list](https://anythingmc.xyz/server/info/lists/server_software/) and the non-premium ones

**Comment by UeberallGebannt** [comment]
Partially fixed by #28.

**Comment by TonimatasDEV** [comment]
More softwares in #35

**Comment by UeberallGebannt** [comment]
@TonimatasDEV Do we have a list of all softwares which have yet to be added?

**Comment by TonimatasDEV** [comment]
> @TonimatasDEV Do we have a list of all softwares which have yet to be added?

I have a list in txt file all software of AnythingMC not added

**Comment by TonimatasDEV** [comment]
I have a document with the remaining AnythingMC software. If you add any of these softwares you can delete it in the document commenting it, when I confirm it I will delete it definitively.

[Document](https://docs.google.com/document/d/1ehLl6Ae66QClDEHuM1YHP8ciNqvTR-0P6A2gPErmajk/edit?usp=sharing)

Close https://github.com/UeberallGebannt/server-softwares/issues/24

**Comment by TonimatasDEV** [comment]
More softwares #61 
Remaining: 88

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by LeStegii** [comment]
Yea, the project is still active

> ### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".
