### ISSUE TITLE
[SOFTWARES] Add multiple softwares 

### ISSUE THREAD

**Issue by LeStegii** [LeStegii/server-softwares#45]
https://github.com/haveachin/infrared
https://github.com/PrismarineJS/flying-squid
https://github.com/ObsidianMC/Obsidian
https://github.com/hpi-swa/native-minecraft-server

**Comment by UeberallGebannt** [comment]
Partially fixed in #46.

**TODO**
https://github.com/hpi-swa/native-minecraft-server
https://github.com/haveachin/infrared
