### ISSUE TITLE
For DirtyFolia's description of the plugin types 

### ISSUE THREAD

**Issue by killerprojecte** [LeStegii/server-softwares#59]
I think the description of the plugin types supported by DirtyFolia is incorrect.
DirtyFolia supports part of the Bukkit/Spigot plugin interface.
I think changing to "Folia (Bukkit [incomplete]/Spigot [incomplete]/Paper)" might be more appropriate.

**Comment by LeStegii** [comment]
Folia is in a quite unusual state when it comes to api support, as most spigot plugins will work out of the box but have to specify folia support in the plugin.yml if I remember correctly.

But you're right, I will add a note 👍

**Comment by LeStegii** [comment]
@killerprojecte Could you check #60?
