### ISSUE TITLE
[SOFTWARE] Feather -> valence

### ISSUE THREAD

**Issue by SnowCutieOwO** [LeStegii/server-softwares#82]
**What is the name of the software?**
Feather
valence

**Describe what the server is in 1-2 sentences.**
A server coded in Rust and provided better performance.

**What type of mods/plugins does the software support?**
Plugins.

**What version does the software support?**
Unknown, it does not show anything about version support

**Additional information**
I hope you could turn your all these files into wiki so we could have a better reading experience.
;)

**Comment by LeStegii** [comment]
Are you talking about this? https://github.com/valence-rs/valence

Because we already got feather.

**Comment by SnowCutieOwO** [comment]
> Are you talking about this? https://github.com/valence-rs/valence
> 
> Because we already got feather.

Yes, since the Valence is the continue of Feather. May you add it later?

**Comment by LeStegii** [comment]
Yep absolutely. Also @lunofe is currently working on a wiki like web page that will mirror our github page.
This should be easier to maintain and style than a regular github wiki.

**Comment by LeStegii** [comment]
Added in [cb16514](https://github.com/LeStegii/server-softwares/commit/cb1651409f70b211ffae778beb98afb29e49dce3)
