### ISSUE TITLE
"Lost" category

### ISSUE THREAD

**Issue by LeStegii** [LeStegii/server-softwares#92]
## Idea
A lost category would contain all the softwares that don't have a repository or download link available.

## Why?
Currently lost softawres are included in the other files which makes it hard to differentiate between abandoned and lost softwares.
If you think you found a software fitting your needs, you might find out it's lost to time.

## Problems/Discussions
We'd have to decide if softwares like Cauldron, where there is no official repo anymore, should count as lost.

**Comment by ll-KOYA-ll** [comment]
I think this is a good idea. For the download link, I'm assuming that its always the official download link? 

Also for the discussion section, I was thinking that if a software has inactive development, no official repo, and no official link should be considered lost. Last thing is that what if for an extreme case should a server software suddenly becomes active again (official repo/link reappears)? I'm guessing that it would get removed from the "Lost" category?

**Comment by LeStegii** [comment]
Yes, inactive softwars wouldn't be moved to lost most likely, but I'd be open to that.
However, inactive softwares might become active again, while lost softwares should stay "lost".
