### ISSUE TITLE
Text Readability on Website

### ISSUE THREAD

**Issue by ll-KOYA-ll** [LeStegii/server-softwares#93]
Problem:

The website that lists the server software has an element that shows the user that the following server software is discontinued/inactive but the text telling the user this warning message is hard to read. 

Example of the problem:
![image](https://github.com/LeStegii/server-softwares/assets/69911566/98d485ff-a4fa-4bb6-afed-391adc225d10)

Solution:

A small fix would be to just change the font color so that it makes it easier to read (preferably white).

**Comment by lunofe** [comment]
This is because your browser somehow forces the light theme to be used. Do you use any sort of extensions/settings/etc that tinker with this?

**Comment by LeStegii** [comment]
Could you link the exact origin of this image? Because I checked and it isn't as dark for me.
![grafik](https://github.com/LeStegii/server-softwares/assets/50475262/c97b4d86-ad3d-4a6a-af9d-d13d69fe34ce)

**Comment by lunofe** [comment]
Should be fixed in https://github.com/lunofe/mcss-frontend/commit/26b82d1b55de991fbaa0e842bfb36bc9616a66f5

**Comment by ll-KOYA-ll** [comment]
I used librewolf when viewing the site and the only extension I used was uBlock. I believe that since its librewolf, there's probably a setting in the background that results in the site forcing light theme. I tried with chrome/edge and the site forces dark mode and the text is readable.
