### ISSUE TITLE
The plural of "software" is "software"

### ISSUE THREAD

**Issue by LeStegii** [LeStegii/server-softwares#94]
The plural of "software" is "software", not "softwares".
As this hasn't become obvious to anyone yet, it seems to be a minor issue, but it might be worth changing the repo and names.

**Comment by LeStegii** [comment]
@lunofe Would anything break in mcss-frontend when changing the repo name here? I don't know if and for how long github keeps old repo names.

**Comment by lunofe** [comment]
Yes, but it's a quick fix.

- A couple of links in README.md & the website's footer
- GitHub Workflow checks out the repo by name
